import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { ProductsSide } from "@/components/ProductsSide";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Header/>
        <div className=" flex gap-x-2 sm:gap-x-4 max-w-[1600px] mx-auto">
        
          <div className="w-4/12 max-w-60 relative pt-18">
            <ProductsSide />
          </div>
        <div className="pt-16 w-10/12 ">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
